my:
  data:
    prod-id: 555
    prod-code: AT
    prod-cost: 6.3
    prod-modules:
    - M1
    - M2
    prod-versions:
      V1: 1.0-SNAPSHOT
      V2: 1.0-BUILD
    mod-info:
      module-code: META
      module-ver: 2
---
spring:
  profiles:
    active:
    - dev
my:
  data:
    prod-id: 666          